#############################################################################
# Makefile for building: FireFighterRemoteUnit
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  FireFighterRemoteUnit.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -o Makefile FireFighterRemoteUnit.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -std=c++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/ros/kinetic/include -I/opt/ros/kinetic/lib/x86_64-linux-gnu -I~/SLAM_BASE/OpenCV/build/include/opencv4/ -I../../../../OpenCV/build/include -I/usr/lib/x86_64-linux-gnu -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = FireFighterRemoteUnit1.0.0
DISTDIR = /home/nawar/SLAM_BASE/ORB_SLAM2/catkin_ws/src/firefighterremoteunit/.tmp/FireFighterRemoteUnit1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1 -Wl,-rpath,/opt/ros/kinetic/lib
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -L/usr/lib/x86_64-linux-gnu/ -lrealsense2 -L/opt/ros/kinetic/lib/ -lroscpp -lroscpp_serialization -lrosconsole -lrostime -lcv_bridge -limage_transport -L/opt/ros/kinetic/lib/x86_64-linux-gnu/ -lopencv_core3 -lopencv_imgcodecs3 -lopencv_imgproc3 -L~/SLAM_BASE/OpenCV/build/lib/ -L/home/nawar/SLAM_BASE/ORB_SLAM2/catkin_ws/src/firefighterremoteunit/../../../../OpenCV/build/lib/ -lopencv_core -L/home/nawar/SLAM_BASE/ORB_SLAM2/catkin_ws/src/firefighterremoteunit/../../../../../../../usr/lib/x86_64-linux-gnu/ -lglfw -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainWindow.cpp \
		rosNodeWidget.cpp \
		viewerWidget.cpp moc_mainWindow.cpp \
		moc_rosNodeWidget.cpp
OBJECTS       = main.o \
		mainWindow.o \
		rosNodeWidget.o \
		viewerWidget.o \
		moc_mainWindow.o \
		moc_rosNodeWidget.o
DIST          = firefighterremoteunit.qmodel \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		FireFighterRemoteUnit.pro mainWindow.hpp \
		rosNodeWidget.hpp \
		viewerWidget.hpp main.cpp \
		mainWindow.cpp \
		rosNodeWidget.cpp \
		viewerWidget.cpp
QMAKE_TARGET  = FireFighterRemoteUnit
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = FireFighterRemoteUnit


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FireFighterRemoteUnit.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		FireFighterRemoteUnit.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile FireFighterRemoteUnit.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/c++11.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
FireFighterRemoteUnit.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile FireFighterRemoteUnit.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainWindow.hpp rosNodeWidget.hpp viewerWidget.hpp $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainWindow.cpp rosNodeWidget.cpp viewerWidget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainWindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainWindow.cpp moc_rosNodeWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainWindow.cpp moc_rosNodeWidget.cpp
moc_mainWindow.cpp: rosNodeWidget.hpp \
		/opt/ros/kinetic/include/ros/ros.h \
		/opt/ros/kinetic/include/ros/time.h \
		/opt/ros/kinetic/include/ros/platform.h \
		/opt/ros/kinetic/include/ros/exception.h \
		/opt/ros/kinetic/include/ros/duration.h \
		/opt/ros/kinetic/include/ros/rostime_decl.h \
		/opt/ros/kinetic/include/ros/macros.h \
		/opt/ros/kinetic/include/ros/rate.h \
		/opt/ros/kinetic/include/ros/console.h \
		/opt/ros/kinetic/include/ros/console_backend.h \
		/opt/ros/kinetic/include/rosconsole/macros_generated.h \
		/opt/ros/kinetic/include/ros/assert.h \
		/opt/ros/kinetic/include/ros/static_assert.h \
		/opt/ros/kinetic/include/ros/common.h \
		/opt/ros/kinetic/include/ros/forwards.h \
		/opt/ros/kinetic/include/ros/exceptions.h \
		/opt/ros/kinetic/include/ros/datatypes.h \
		/opt/ros/kinetic/include/ros/serialized_message.h \
		/opt/ros/kinetic/include/ros/roscpp_serialization_macros.h \
		/opt/ros/kinetic/include/ros/types.h \
		/opt/ros/kinetic/include/ros/node_handle.h \
		/opt/ros/kinetic/include/ros/publisher.h \
		/opt/ros/kinetic/include/ros/message.h \
		/opt/ros/kinetic/include/ros/serialization.h \
		/opt/ros/kinetic/include/ros/message_traits.h \
		/opt/ros/kinetic/include/ros/message_forward.h \
		/opt/ros/kinetic/include/ros/builtin_message_traits.h \
		/opt/ros/kinetic/include/ros/subscriber.h \
		/opt/ros/kinetic/include/ros/subscription_callback_helper.h \
		/opt/ros/kinetic/include/ros/parameter_adapter.h \
		/opt/ros/kinetic/include/ros/message_event.h \
		/opt/ros/kinetic/include/ros/service_server.h \
		/opt/ros/kinetic/include/ros/service_client.h \
		/opt/ros/kinetic/include/ros/service_traits.h \
		/opt/ros/kinetic/include/ros/timer.h \
		/opt/ros/kinetic/include/ros/timer_options.h \
		/opt/ros/kinetic/include/ros/wall_timer.h \
		/opt/ros/kinetic/include/ros/wall_timer_options.h \
		/opt/ros/kinetic/include/ros/steady_timer.h \
		/opt/ros/kinetic/include/ros/steady_timer_options.h \
		/opt/ros/kinetic/include/ros/advertise_options.h \
		/opt/ros/kinetic/include/ros/advertise_service_options.h \
		/opt/ros/kinetic/include/ros/service_callback_helper.h \
		/opt/ros/kinetic/include/ros/subscribe_options.h \
		/opt/ros/kinetic/include/ros/transport_hints.h \
		/opt/ros/kinetic/include/ros/service_client_options.h \
		/opt/ros/kinetic/include/ros/spinner.h \
		/opt/ros/kinetic/include/ros/init.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcValue.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcDecl.h \
		/opt/ros/kinetic/include/ros/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/ros/service.h \
		/opt/ros/kinetic/include/ros/names.h \
		/opt/ros/kinetic/include/ros/master.h \
		/opt/ros/kinetic/include/ros/this_node.h \
		/opt/ros/kinetic/include/ros/param.h \
		/opt/ros/kinetic/include/ros/topic.h \
		/opt/ros/kinetic/include/std_msgs/String.h \
		/opt/ros/kinetic/include/ros/message_operations.h \
		/opt/ros/kinetic/include/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/cv_bridge/cv_bridge.h \
		/opt/ros/kinetic/include/sensor_msgs/Image.h \
		/opt/ros/kinetic/include/std_msgs/Header.h \
		/opt/ros/kinetic/include/sensor_msgs/CompressedImage.h \
		/opt/ros/kinetic/include/sensor_msgs/image_encodings.h \
		/opt/ros/kinetic/include/opencv2/core/core.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/image_transport/image_transport.h \
		/opt/ros/kinetic/include/image_transport/publisher.h \
		/opt/ros/kinetic/include/image_transport/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/image_transport/exception.h \
		/opt/ros/kinetic/include/image_transport/loader_fwds.h \
		/opt/ros/kinetic/include/image_transport/subscriber.h \
		/opt/ros/kinetic/include/image_transport/transport_hints.h \
		/opt/ros/kinetic/include/image_transport/camera_publisher.h \
		/opt/ros/kinetic/include/sensor_msgs/CameraInfo.h \
		/opt/ros/kinetic/include/sensor_msgs/RegionOfInterest.h \
		/opt/ros/kinetic/include/image_transport/camera_subscriber.h \
		viewerWidget.hpp \
		/usr/lib/x86_64-linux-gnu/glfw/include/GLFW/glfw3.h \
		ui_mainWindow.h \
		mainWindow.hpp
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nawar/SLAM_BASE/ORB_SLAM2/catkin_ws/src/firefighterremoteunit -I/opt/ros/kinetic/include -I/opt/ros/kinetic/lib/x86_64-linux-gnu -I'/home/nawar/SLAM_BASE/ORB_SLAM2/catkin_ws/src/firefighterremoteunit/~/SLAM_BASE/OpenCV/build/include/opencv4' -I/home/nawar/SLAM_BASE/OpenCV/build/include -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainWindow.hpp -o moc_mainWindow.cpp

moc_rosNodeWidget.cpp: /opt/ros/kinetic/include/ros/ros.h \
		/opt/ros/kinetic/include/ros/time.h \
		/opt/ros/kinetic/include/ros/platform.h \
		/opt/ros/kinetic/include/ros/exception.h \
		/opt/ros/kinetic/include/ros/duration.h \
		/opt/ros/kinetic/include/ros/rostime_decl.h \
		/opt/ros/kinetic/include/ros/macros.h \
		/opt/ros/kinetic/include/ros/rate.h \
		/opt/ros/kinetic/include/ros/console.h \
		/opt/ros/kinetic/include/ros/console_backend.h \
		/opt/ros/kinetic/include/rosconsole/macros_generated.h \
		/opt/ros/kinetic/include/ros/assert.h \
		/opt/ros/kinetic/include/ros/static_assert.h \
		/opt/ros/kinetic/include/ros/common.h \
		/opt/ros/kinetic/include/ros/forwards.h \
		/opt/ros/kinetic/include/ros/exceptions.h \
		/opt/ros/kinetic/include/ros/datatypes.h \
		/opt/ros/kinetic/include/ros/serialized_message.h \
		/opt/ros/kinetic/include/ros/roscpp_serialization_macros.h \
		/opt/ros/kinetic/include/ros/types.h \
		/opt/ros/kinetic/include/ros/node_handle.h \
		/opt/ros/kinetic/include/ros/publisher.h \
		/opt/ros/kinetic/include/ros/message.h \
		/opt/ros/kinetic/include/ros/serialization.h \
		/opt/ros/kinetic/include/ros/message_traits.h \
		/opt/ros/kinetic/include/ros/message_forward.h \
		/opt/ros/kinetic/include/ros/builtin_message_traits.h \
		/opt/ros/kinetic/include/ros/subscriber.h \
		/opt/ros/kinetic/include/ros/subscription_callback_helper.h \
		/opt/ros/kinetic/include/ros/parameter_adapter.h \
		/opt/ros/kinetic/include/ros/message_event.h \
		/opt/ros/kinetic/include/ros/service_server.h \
		/opt/ros/kinetic/include/ros/service_client.h \
		/opt/ros/kinetic/include/ros/service_traits.h \
		/opt/ros/kinetic/include/ros/timer.h \
		/opt/ros/kinetic/include/ros/timer_options.h \
		/opt/ros/kinetic/include/ros/wall_timer.h \
		/opt/ros/kinetic/include/ros/wall_timer_options.h \
		/opt/ros/kinetic/include/ros/steady_timer.h \
		/opt/ros/kinetic/include/ros/steady_timer_options.h \
		/opt/ros/kinetic/include/ros/advertise_options.h \
		/opt/ros/kinetic/include/ros/advertise_service_options.h \
		/opt/ros/kinetic/include/ros/service_callback_helper.h \
		/opt/ros/kinetic/include/ros/subscribe_options.h \
		/opt/ros/kinetic/include/ros/transport_hints.h \
		/opt/ros/kinetic/include/ros/service_client_options.h \
		/opt/ros/kinetic/include/ros/spinner.h \
		/opt/ros/kinetic/include/ros/init.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcValue.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcDecl.h \
		/opt/ros/kinetic/include/ros/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/ros/service.h \
		/opt/ros/kinetic/include/ros/names.h \
		/opt/ros/kinetic/include/ros/master.h \
		/opt/ros/kinetic/include/ros/this_node.h \
		/opt/ros/kinetic/include/ros/param.h \
		/opt/ros/kinetic/include/ros/topic.h \
		/opt/ros/kinetic/include/std_msgs/String.h \
		/opt/ros/kinetic/include/ros/message_operations.h \
		/opt/ros/kinetic/include/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/cv_bridge/cv_bridge.h \
		/opt/ros/kinetic/include/sensor_msgs/Image.h \
		/opt/ros/kinetic/include/std_msgs/Header.h \
		/opt/ros/kinetic/include/sensor_msgs/CompressedImage.h \
		/opt/ros/kinetic/include/sensor_msgs/image_encodings.h \
		/opt/ros/kinetic/include/opencv2/core/core.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/image_transport/image_transport.h \
		/opt/ros/kinetic/include/image_transport/publisher.h \
		/opt/ros/kinetic/include/image_transport/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/image_transport/exception.h \
		/opt/ros/kinetic/include/image_transport/loader_fwds.h \
		/opt/ros/kinetic/include/image_transport/subscriber.h \
		/opt/ros/kinetic/include/image_transport/transport_hints.h \
		/opt/ros/kinetic/include/image_transport/camera_publisher.h \
		/opt/ros/kinetic/include/sensor_msgs/CameraInfo.h \
		/opt/ros/kinetic/include/sensor_msgs/RegionOfInterest.h \
		/opt/ros/kinetic/include/image_transport/camera_subscriber.h \
		rosNodeWidget.hpp
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/home/nawar/SLAM_BASE/ORB_SLAM2/catkin_ws/src/firefighterremoteunit -I/opt/ros/kinetic/include -I/opt/ros/kinetic/lib/x86_64-linux-gnu -I'/home/nawar/SLAM_BASE/ORB_SLAM2/catkin_ws/src/firefighterremoteunit/~/SLAM_BASE/OpenCV/build/include/opencv4' -I/home/nawar/SLAM_BASE/OpenCV/build/include -I/usr/lib/x86_64-linux-gnu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include rosNodeWidget.hpp -o moc_rosNodeWidget.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainWindow.h
ui_mainWindow.h: mainWindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic mainWindow.ui -o ui_mainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainWindow.hpp \
		rosNodeWidget.hpp \
		/opt/ros/kinetic/include/ros/ros.h \
		/opt/ros/kinetic/include/ros/time.h \
		/opt/ros/kinetic/include/ros/platform.h \
		/opt/ros/kinetic/include/ros/exception.h \
		/opt/ros/kinetic/include/ros/duration.h \
		/opt/ros/kinetic/include/ros/rostime_decl.h \
		/opt/ros/kinetic/include/ros/macros.h \
		/opt/ros/kinetic/include/ros/rate.h \
		/opt/ros/kinetic/include/ros/console.h \
		/opt/ros/kinetic/include/ros/console_backend.h \
		/opt/ros/kinetic/include/rosconsole/macros_generated.h \
		/opt/ros/kinetic/include/ros/assert.h \
		/opt/ros/kinetic/include/ros/static_assert.h \
		/opt/ros/kinetic/include/ros/common.h \
		/opt/ros/kinetic/include/ros/forwards.h \
		/opt/ros/kinetic/include/ros/exceptions.h \
		/opt/ros/kinetic/include/ros/datatypes.h \
		/opt/ros/kinetic/include/ros/serialized_message.h \
		/opt/ros/kinetic/include/ros/roscpp_serialization_macros.h \
		/opt/ros/kinetic/include/ros/types.h \
		/opt/ros/kinetic/include/ros/node_handle.h \
		/opt/ros/kinetic/include/ros/publisher.h \
		/opt/ros/kinetic/include/ros/message.h \
		/opt/ros/kinetic/include/ros/serialization.h \
		/opt/ros/kinetic/include/ros/message_traits.h \
		/opt/ros/kinetic/include/ros/message_forward.h \
		/opt/ros/kinetic/include/ros/builtin_message_traits.h \
		/opt/ros/kinetic/include/ros/subscriber.h \
		/opt/ros/kinetic/include/ros/subscription_callback_helper.h \
		/opt/ros/kinetic/include/ros/parameter_adapter.h \
		/opt/ros/kinetic/include/ros/message_event.h \
		/opt/ros/kinetic/include/ros/service_server.h \
		/opt/ros/kinetic/include/ros/service_client.h \
		/opt/ros/kinetic/include/ros/service_traits.h \
		/opt/ros/kinetic/include/ros/timer.h \
		/opt/ros/kinetic/include/ros/timer_options.h \
		/opt/ros/kinetic/include/ros/wall_timer.h \
		/opt/ros/kinetic/include/ros/wall_timer_options.h \
		/opt/ros/kinetic/include/ros/steady_timer.h \
		/opt/ros/kinetic/include/ros/steady_timer_options.h \
		/opt/ros/kinetic/include/ros/advertise_options.h \
		/opt/ros/kinetic/include/ros/advertise_service_options.h \
		/opt/ros/kinetic/include/ros/service_callback_helper.h \
		/opt/ros/kinetic/include/ros/subscribe_options.h \
		/opt/ros/kinetic/include/ros/transport_hints.h \
		/opt/ros/kinetic/include/ros/service_client_options.h \
		/opt/ros/kinetic/include/ros/spinner.h \
		/opt/ros/kinetic/include/ros/init.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcValue.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcDecl.h \
		/opt/ros/kinetic/include/ros/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/ros/service.h \
		/opt/ros/kinetic/include/ros/names.h \
		/opt/ros/kinetic/include/ros/master.h \
		/opt/ros/kinetic/include/ros/this_node.h \
		/opt/ros/kinetic/include/ros/param.h \
		/opt/ros/kinetic/include/ros/topic.h \
		/opt/ros/kinetic/include/std_msgs/String.h \
		/opt/ros/kinetic/include/ros/message_operations.h \
		/opt/ros/kinetic/include/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/cv_bridge/cv_bridge.h \
		/opt/ros/kinetic/include/sensor_msgs/Image.h \
		/opt/ros/kinetic/include/std_msgs/Header.h \
		/opt/ros/kinetic/include/sensor_msgs/CompressedImage.h \
		/opt/ros/kinetic/include/sensor_msgs/image_encodings.h \
		/opt/ros/kinetic/include/opencv2/core/core.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/image_transport/image_transport.h \
		/opt/ros/kinetic/include/image_transport/publisher.h \
		/opt/ros/kinetic/include/image_transport/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/image_transport/exception.h \
		/opt/ros/kinetic/include/image_transport/loader_fwds.h \
		/opt/ros/kinetic/include/image_transport/subscriber.h \
		/opt/ros/kinetic/include/image_transport/transport_hints.h \
		/opt/ros/kinetic/include/image_transport/camera_publisher.h \
		/opt/ros/kinetic/include/sensor_msgs/CameraInfo.h \
		/opt/ros/kinetic/include/sensor_msgs/RegionOfInterest.h \
		/opt/ros/kinetic/include/image_transport/camera_subscriber.h \
		viewerWidget.hpp \
		/usr/lib/x86_64-linux-gnu/glfw/include/GLFW/glfw3.h \
		ui_mainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainWindow.o: mainWindow.cpp mainWindow.hpp \
		rosNodeWidget.hpp \
		/opt/ros/kinetic/include/ros/ros.h \
		/opt/ros/kinetic/include/ros/time.h \
		/opt/ros/kinetic/include/ros/platform.h \
		/opt/ros/kinetic/include/ros/exception.h \
		/opt/ros/kinetic/include/ros/duration.h \
		/opt/ros/kinetic/include/ros/rostime_decl.h \
		/opt/ros/kinetic/include/ros/macros.h \
		/opt/ros/kinetic/include/ros/rate.h \
		/opt/ros/kinetic/include/ros/console.h \
		/opt/ros/kinetic/include/ros/console_backend.h \
		/opt/ros/kinetic/include/rosconsole/macros_generated.h \
		/opt/ros/kinetic/include/ros/assert.h \
		/opt/ros/kinetic/include/ros/static_assert.h \
		/opt/ros/kinetic/include/ros/common.h \
		/opt/ros/kinetic/include/ros/forwards.h \
		/opt/ros/kinetic/include/ros/exceptions.h \
		/opt/ros/kinetic/include/ros/datatypes.h \
		/opt/ros/kinetic/include/ros/serialized_message.h \
		/opt/ros/kinetic/include/ros/roscpp_serialization_macros.h \
		/opt/ros/kinetic/include/ros/types.h \
		/opt/ros/kinetic/include/ros/node_handle.h \
		/opt/ros/kinetic/include/ros/publisher.h \
		/opt/ros/kinetic/include/ros/message.h \
		/opt/ros/kinetic/include/ros/serialization.h \
		/opt/ros/kinetic/include/ros/message_traits.h \
		/opt/ros/kinetic/include/ros/message_forward.h \
		/opt/ros/kinetic/include/ros/builtin_message_traits.h \
		/opt/ros/kinetic/include/ros/subscriber.h \
		/opt/ros/kinetic/include/ros/subscription_callback_helper.h \
		/opt/ros/kinetic/include/ros/parameter_adapter.h \
		/opt/ros/kinetic/include/ros/message_event.h \
		/opt/ros/kinetic/include/ros/service_server.h \
		/opt/ros/kinetic/include/ros/service_client.h \
		/opt/ros/kinetic/include/ros/service_traits.h \
		/opt/ros/kinetic/include/ros/timer.h \
		/opt/ros/kinetic/include/ros/timer_options.h \
		/opt/ros/kinetic/include/ros/wall_timer.h \
		/opt/ros/kinetic/include/ros/wall_timer_options.h \
		/opt/ros/kinetic/include/ros/steady_timer.h \
		/opt/ros/kinetic/include/ros/steady_timer_options.h \
		/opt/ros/kinetic/include/ros/advertise_options.h \
		/opt/ros/kinetic/include/ros/advertise_service_options.h \
		/opt/ros/kinetic/include/ros/service_callback_helper.h \
		/opt/ros/kinetic/include/ros/subscribe_options.h \
		/opt/ros/kinetic/include/ros/transport_hints.h \
		/opt/ros/kinetic/include/ros/service_client_options.h \
		/opt/ros/kinetic/include/ros/spinner.h \
		/opt/ros/kinetic/include/ros/init.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcValue.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcDecl.h \
		/opt/ros/kinetic/include/ros/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/ros/service.h \
		/opt/ros/kinetic/include/ros/names.h \
		/opt/ros/kinetic/include/ros/master.h \
		/opt/ros/kinetic/include/ros/this_node.h \
		/opt/ros/kinetic/include/ros/param.h \
		/opt/ros/kinetic/include/ros/topic.h \
		/opt/ros/kinetic/include/std_msgs/String.h \
		/opt/ros/kinetic/include/ros/message_operations.h \
		/opt/ros/kinetic/include/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/cv_bridge/cv_bridge.h \
		/opt/ros/kinetic/include/sensor_msgs/Image.h \
		/opt/ros/kinetic/include/std_msgs/Header.h \
		/opt/ros/kinetic/include/sensor_msgs/CompressedImage.h \
		/opt/ros/kinetic/include/sensor_msgs/image_encodings.h \
		/opt/ros/kinetic/include/opencv2/core/core.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/image_transport/image_transport.h \
		/opt/ros/kinetic/include/image_transport/publisher.h \
		/opt/ros/kinetic/include/image_transport/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/image_transport/exception.h \
		/opt/ros/kinetic/include/image_transport/loader_fwds.h \
		/opt/ros/kinetic/include/image_transport/subscriber.h \
		/opt/ros/kinetic/include/image_transport/transport_hints.h \
		/opt/ros/kinetic/include/image_transport/camera_publisher.h \
		/opt/ros/kinetic/include/sensor_msgs/CameraInfo.h \
		/opt/ros/kinetic/include/sensor_msgs/RegionOfInterest.h \
		/opt/ros/kinetic/include/image_transport/camera_subscriber.h \
		viewerWidget.hpp \
		/usr/lib/x86_64-linux-gnu/glfw/include/GLFW/glfw3.h \
		ui_mainWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o mainWindow.cpp

rosNodeWidget.o: rosNodeWidget.cpp rosNodeWidget.hpp \
		/opt/ros/kinetic/include/ros/ros.h \
		/opt/ros/kinetic/include/ros/time.h \
		/opt/ros/kinetic/include/ros/platform.h \
		/opt/ros/kinetic/include/ros/exception.h \
		/opt/ros/kinetic/include/ros/duration.h \
		/opt/ros/kinetic/include/ros/rostime_decl.h \
		/opt/ros/kinetic/include/ros/macros.h \
		/opt/ros/kinetic/include/ros/rate.h \
		/opt/ros/kinetic/include/ros/console.h \
		/opt/ros/kinetic/include/ros/console_backend.h \
		/opt/ros/kinetic/include/rosconsole/macros_generated.h \
		/opt/ros/kinetic/include/ros/assert.h \
		/opt/ros/kinetic/include/ros/static_assert.h \
		/opt/ros/kinetic/include/ros/common.h \
		/opt/ros/kinetic/include/ros/forwards.h \
		/opt/ros/kinetic/include/ros/exceptions.h \
		/opt/ros/kinetic/include/ros/datatypes.h \
		/opt/ros/kinetic/include/ros/serialized_message.h \
		/opt/ros/kinetic/include/ros/roscpp_serialization_macros.h \
		/opt/ros/kinetic/include/ros/types.h \
		/opt/ros/kinetic/include/ros/node_handle.h \
		/opt/ros/kinetic/include/ros/publisher.h \
		/opt/ros/kinetic/include/ros/message.h \
		/opt/ros/kinetic/include/ros/serialization.h \
		/opt/ros/kinetic/include/ros/message_traits.h \
		/opt/ros/kinetic/include/ros/message_forward.h \
		/opt/ros/kinetic/include/ros/builtin_message_traits.h \
		/opt/ros/kinetic/include/ros/subscriber.h \
		/opt/ros/kinetic/include/ros/subscription_callback_helper.h \
		/opt/ros/kinetic/include/ros/parameter_adapter.h \
		/opt/ros/kinetic/include/ros/message_event.h \
		/opt/ros/kinetic/include/ros/service_server.h \
		/opt/ros/kinetic/include/ros/service_client.h \
		/opt/ros/kinetic/include/ros/service_traits.h \
		/opt/ros/kinetic/include/ros/timer.h \
		/opt/ros/kinetic/include/ros/timer_options.h \
		/opt/ros/kinetic/include/ros/wall_timer.h \
		/opt/ros/kinetic/include/ros/wall_timer_options.h \
		/opt/ros/kinetic/include/ros/steady_timer.h \
		/opt/ros/kinetic/include/ros/steady_timer_options.h \
		/opt/ros/kinetic/include/ros/advertise_options.h \
		/opt/ros/kinetic/include/ros/advertise_service_options.h \
		/opt/ros/kinetic/include/ros/service_callback_helper.h \
		/opt/ros/kinetic/include/ros/subscribe_options.h \
		/opt/ros/kinetic/include/ros/transport_hints.h \
		/opt/ros/kinetic/include/ros/service_client_options.h \
		/opt/ros/kinetic/include/ros/spinner.h \
		/opt/ros/kinetic/include/ros/init.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcValue.h \
		/opt/ros/kinetic/include/xmlrpcpp/XmlRpcDecl.h \
		/opt/ros/kinetic/include/ros/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/ros/service.h \
		/opt/ros/kinetic/include/ros/names.h \
		/opt/ros/kinetic/include/ros/master.h \
		/opt/ros/kinetic/include/ros/this_node.h \
		/opt/ros/kinetic/include/ros/param.h \
		/opt/ros/kinetic/include/ros/topic.h \
		/opt/ros/kinetic/include/std_msgs/String.h \
		/opt/ros/kinetic/include/ros/message_operations.h \
		/opt/ros/kinetic/include/opencv2/core.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvdef.h \
		/opt/ros/kinetic/include/opencv2/core/hal/interface.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_dispatch.h \
		/opt/ros/kinetic/include/opencv2/core/cv_cpu_helper.h \
		/opt/ros/kinetic/include/opencv2/core/version.hpp \
		/opt/ros/kinetic/include/opencv2/core/base.hpp \
		/opt/ros/kinetic/include/opencv2/opencv_modules.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.hpp \
		/opt/ros/kinetic/include/opencv2/core/ptr.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/neon_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/vsx_utils.hpp \
		/opt/ros/kinetic/include/opencv2/core/traits.hpp \
		/opt/ros/kinetic/include/opencv2/core/matx.hpp \
		/opt/ros/kinetic/include/opencv2/core/saturate.hpp \
		/opt/ros/kinetic/include/opencv2/core/fast_math.hpp \
		/opt/ros/kinetic/include/opencv2/core/types.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.hpp \
		/opt/ros/kinetic/include/opencv2/core/bufferpool.hpp \
		/opt/ros/kinetic/include/opencv2/core/mat.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/persistence.hpp \
		/opt/ros/kinetic/include/opencv2/core/operations.hpp \
		/opt/ros/kinetic/include/opencv2/core/cvstd.inl.hpp \
		/opt/ros/kinetic/include/opencv2/core/utility.hpp \
		/opt/ros/kinetic/include/opencv2/core/core_c.h \
		/opt/ros/kinetic/include/opencv2/core/types_c.h \
		/opt/ros/kinetic/include/opencv2/core/optim.hpp \
		/opt/ros/kinetic/include/opencv2/core/ovx.hpp \
		/opt/ros/kinetic/include/cv_bridge/cv_bridge.h \
		/opt/ros/kinetic/include/sensor_msgs/Image.h \
		/opt/ros/kinetic/include/std_msgs/Header.h \
		/opt/ros/kinetic/include/sensor_msgs/CompressedImage.h \
		/opt/ros/kinetic/include/sensor_msgs/image_encodings.h \
		/opt/ros/kinetic/include/opencv2/core/core.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc.hpp \
		/opt/ros/kinetic/include/opencv2/imgproc/imgproc_c.h \
		/opt/ros/kinetic/include/opencv2/imgproc/types_c.h \
		/opt/ros/kinetic/include/image_transport/image_transport.h \
		/opt/ros/kinetic/include/image_transport/publisher.h \
		/opt/ros/kinetic/include/image_transport/single_subscriber_publisher.h \
		/opt/ros/kinetic/include/image_transport/exception.h \
		/opt/ros/kinetic/include/image_transport/loader_fwds.h \
		/opt/ros/kinetic/include/image_transport/subscriber.h \
		/opt/ros/kinetic/include/image_transport/transport_hints.h \
		/opt/ros/kinetic/include/image_transport/camera_publisher.h \
		/opt/ros/kinetic/include/sensor_msgs/CameraInfo.h \
		/opt/ros/kinetic/include/sensor_msgs/RegionOfInterest.h \
		/opt/ros/kinetic/include/image_transport/camera_subscriber.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rosNodeWidget.o rosNodeWidget.cpp

viewerWidget.o: viewerWidget.cpp viewerWidget.hpp \
		/usr/lib/x86_64-linux-gnu/glfw/include/GLFW/glfw3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o viewerWidget.o viewerWidget.cpp

moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o moc_mainWindow.cpp

moc_rosNodeWidget.o: moc_rosNodeWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rosNodeWidget.o moc_rosNodeWidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

